In [11]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


# the above code is a rank 1 example

# some function in rank 1 arrays

In [12]:
print(arr.shape)

(4,)


In [13]:
arr[1]=5
print(arr)

[1 5 3 4]


# time for rank 2 arrays

In [14]:
ar2=np.array([[1,2,3],[4,5,6]])
print(type(ar2))
print(ar2.shape)
print(ar2)


<class 'numpy.ndarray'>
(2, 3)
[[1 2 3]
 [4 5 6]]


In [16]:
a=np.array([[1],[2],[3],[4]])
print(a.shape)

(4, 1)


# some other ways to create array

In [18]:
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
arr=np.full((2,2),9)
print(arr)

[[9 9]
 [9 9]]


In [20]:
arr=np.full((4,),10)
print(arr)

[10 10 10 10]


In [22]:
arr=np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
arr=np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


In [27]:
arr=np.random.random((2,3))
print (arr)


[[0.49890457 0.24811222 0.93655538]
 [0.53070224 0.55784295 0.70435981]]


# nd array slicing and indexing

In [40]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
ar=arr[1:3,:2]
print(ar)

[[4 5]
 [7 8]]


In [42]:
print(ar[0,1])

5


In [47]:
ar=np.array([1,2,3])
a=np.array([4,5])
for i,j in zip(ar,a):
    print(i,',',j)

1 , 4
2 , 5


In [49]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
row=np.array([0,1,2])
col=np.array([0,1,2])
arr[row,col]+=5
print(arr)

[[ 6  2  3]
 [ 4 10  6]
 [ 7  8 14]]


# boolean indexing

In [50]:
arr[arr%2 ==0]=0
print(arr)

[[0 0 3]
 [0 0 0]
 [7 0 0]]


# datatypes and arithmetic operations

In [51]:
arr=np.array([[1,2,3],[4,5.5,6]],dtype=np.int)
print(arr)

[[1 2 3]
 [4 5 6]]


In [52]:
print(arr+arr)
print(arr-arr)
print(arr*arr)
print(arr/arr)
print(np.sqrt(arr))
print(np.exp(arr))

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
