In [2]:
import numpy as np
arr=np.array([1,2,3,4])
arr


array([1, 2, 3, 4])

# the above code is a rank 1 example

# some function in rank 1 arrays

In [3]:
print(arr.shape)

(4,)


In [4]:
arr[1]=5
print(arr)

[1 5 3 4]


# time for rank 2 arrays

In [5]:
ar2=np.array([[1,2,3],[4,5,6]])
print(type(ar2))
print(ar2.shape)
print(ar2)


<class 'numpy.ndarray'>
(2, 3)
[[1 2 3]
 [4 5 6]]


In [6]:
a=np.array([[1],[2],[3],[4]])
print(a.shape)

(4, 1)


# some other ways to create array

In [7]:
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
arr=np.full((2,2),9)
print(arr)

[[9 9]
 [9 9]]


In [67]:
arr=np.full((4,),10)
print(arr)

[10 10 10 10]


In [69]:
arr=np.eye(5,dtype='int16')
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [11]:
arr=np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


In [12]:
arr=np.random.random((2,3))
print (arr)


[[0.42678113 0.49747836 0.55828277]
 [0.36458019 0.71657008 0.075611  ]]


# nd array slicing and indexing

In [13]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
ar=arr[1:3,:2]
print(ar)

[[4 5]
 [7 8]]


In [15]:
print(ar[0,1])

5


In [16]:
ar=np.array([1,2,3])
a=np.array([4,5])
for i,j in zip(ar,a):
    print(i,',',j)

1 , 4
2 , 5


In [17]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
row=np.array([0,1,2])
col=np.array([0,1,2])
arr[row,col]+=5
print(arr)

[[ 6  2  3]
 [ 4 10  6]
 [ 7  8 14]]


# boolean indexing

In [18]:
arr[arr%2 ==0]=0
print(arr)

[[0 0 3]
 [0 0 0]
 [7 0 0]]


# datatypes and arithmetic operations

In [19]:
arr=np.array([[1,2,3],[4,5.5,6]],dtype=np.int)
print(arr)

[[1 2 3]
 [4 5 6]]


In [20]:
print(arr+arr)
print(arr-arr)
print(arr*arr)
print(arr/arr)
print(np.sqrt(arr))
print(np.exp(arr))

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [21]:
a=np.array([2.5,5.5,7.8],dtype='float')
print(a)
print(a.dtype)

[2.5 5.5 7.8]
float64


In [22]:
b=np.arange(start=19,stop=25)
print(b)

[19 20 21 22 23 24]


In [23]:
c=np.arange(20,25)
print(c)

[20 21 22 23 24]


In [24]:
d=np.arange(20,30,2)
print(d)

[20 22 24 26 28]


In [25]:
f=np.arange(20,30)
print(f.reshape(2,-1))
print(f)

[[20 21 22 23 24]
 [25 26 27 28 29]]
[20 21 22 23 24 25 26 27 28 29]


In [26]:
g=np.arange(20,30)
g.resize(2,5)
print (g)

[[20 21 22 23 24]
 [25 26 27 28 29]]


## reshape does not alters original array .. resize alters original array 

### in reshape we can give negative numbers as argument ... its value will be automatically calculated by the corresponding parameter.

In [57]:
val=np.array([1,2,3,np.nan])
print(val.sum())

nan


## to ignore np values while taking sum     to check for nan values

In [58]:
np.nansum(val)

6.0

In [59]:
print(np.isnan(val))

[False False False  True]


In [60]:
g=np.array([ [1,2,3], [4,5,6]  ])
print(g) 

[[1 2 3]
 [4 5 6]]


In [61]:
g.ndim

2

In [62]:
a.ndim

1

In [63]:
g.size

6

In [64]:
g.shape

(2, 3)

## size gives no of elements        Shape gives no of rows and columns

In [38]:
a=np.array([1,2,3],dtype=np.int16)
print(a)

[1 2 3]


In [39]:
b=np.zeros((2,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [41]:
c=np.zeros([2,3])
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


In [43]:
c=np.empty((1,3))
print (c)

[[2.5 5.5 7.8]]


## to get arbitary(uninitialised) values in array of given shape,datatype use empty()

In [53]:
d=np.empty((4,3),dtype='float')
print(d)

[[9.12563345e-312 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 2.37859344e+184]
 [2.00426448e-076 3.14380240e+179 1.00606403e-070]
 [7.87630594e-071 3.15476055e-033 1.61965115e-051]]


In [55]:
e=np.diag([1,2,3])
print(e)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [56]:
f=np.ones((3,3))
print(f)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## to get falttened 1d array from 2d array but doesnot alters the original array

In [73]:
e.ravel()


array([1, 0, 0, 0, 2, 0, 0, 0, 3])

In [74]:
print(e)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [79]:
print(d.reshape(2,-1))

[[9.12563345e-312 3.16202013e-322 0.00000000e+000 0.00000000e+000
  0.00000000e+000 2.37859344e+184]
 [2.00426448e-076 3.14380240e+179 1.00606403e-070 7.87630594e-071
  3.15476055e-033 1.61965115e-051]]


In [80]:
d.resize((2,6))
print(d)

[[9.12563345e-312 3.16202013e-322 0.00000000e+000 0.00000000e+000
  0.00000000e+000 2.37859344e+184]
 [2.00426448e-076 3.14380240e+179 1.00606403e-070 7.87630594e-071
  3.15476055e-033 1.61965115e-051]]


In [84]:
a=np.array([[1,2,3],[3,4,5]])
print(a)

[[1 2 3]
 [3 4 5]]


In [85]:
print(a.T)

[[1 3]
 [2 4]
 [3 5]]


In [86]:
print(a)

[[1 2 3]
 [3 4 5]]


# transpose does not modify original array

In [108]:
np.trace(a)

5

In [109]:
np.trace(e)

6

In [110]:
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [111]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# gives inverse but the values are in floating point

In [112]:
b=np.array([[7,8],[10,11]])

In [113]:
a+b

array([[ 8, 10],
       [13, 15]])

In [114]:
a-b

array([[-6, -6],
       [-7, -7]])

In [115]:
ainv=np.array([[-2,1],[1.5,-.5]])

In [116]:
a.dot(ainv)

array([[1., 0.],
       [0., 1.]])

# for matrix multiplication

# NOW ,to solve AX=B  use np.linalg.solve(A,B)

In [118]:
e=np.eye(2)
np.linalg.solve(a,e)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])